name: RawBuildTest
on: [push]
jobs:
  BuildImpishRaw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Satify Dependencies
        run: sudo apt update; sudo apt install git build-essential binfmt-support qemu-user-static debootstrap -y
      - name: Trigger fs-cook
        run: bash .github/scripts/build-impish.sh
      - name: save arm64 builds
        uses: actions/upload-artifact@v2
        with:
          name: impish-raw-arm64
          path: /home/runner/work/test-repo-/test-repo-/fs-cook/impish-arm64
      - name: save armhf builds
        uses: actions/upload-artifact@v2
        with:
          name: impish-raw-armhf
          path: /home/runner/work/test-repo-/test-repo-/fs-cook/impish-armhf
      - name: save amd64 builds
        uses: actions/upload-artifact@v2
        with:
          name: impish-raw-amd64
          path: /home/runner/work/test-repo-/test-repo-/fs-cook/impish-amd64
  BuidHirsute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Satify Dependencies
        run: sudo apt update; sudo apt install git build-essential binfmt-support qemu-user-static debootstrap -y
      - name: Trigger fs-cook
        run: bash .github/scripts/build-hirsute.sh
      - name: save arm64 builds
        uses: actions/upload-artifact@v2
        with:
          name: hirsute-raw-arm64
          path: /home/runner/work/test-repo-/test-repo-/fs-cook/hirsute-arm64
      - name: save armhf builds
        uses: actions/upload-artifact@v2
        with:
          name: hirsute-raw-armhf
          path: /home/runner/work/test-repo-/test-repo-/fs-cook/hirsute-armhf
      - name: save amd64 builds
        uses: actions/upload-artifact@v2
        with:
          name: hirsute-raw-amd64
          path: /home/runner/work/test-repo-/test-repo-/fs-cook/hirsute-amd64
      
      